const LEVELS = ["A1", "A2", "B1"];

const LEVEL_META = {
  A1: { title: "起步", de: "Anfang", blurb: "打招呼、点餐、自我介绍。先把日子过起来。" },
  A2: { title: "出门", de: "Unterwegs", blurb: "问路、看病、聊周末。能把一件小事说完整。" },
  B1: { title: "说理", de: "Meinung", blurb: "讲原因、谈计划、表达态度。句子开始有骨头。" },
};

const WORDS = {
  A1: [
    { id: "a1-01", de: "Hallo", art: "", zh: "你好", ipa: "ˈhalo", ex: "Hallo, ich bin Mia.", exZh: "你好，我是米娅。", tag: "问候" },
    { id: "a1-02", de: "Danke", art: "", zh: "谢谢", ipa: "ˈdaŋkə", ex: "Danke für den Kaffee.", exZh: "谢谢这杯咖啡。", tag: "问候" },
    { id: "a1-03", de: "Bitte", art: "", zh: "请 / 不客气", ipa: "ˈbɪtə", ex: "Bitte schön!", exZh: "不客气！ / 请用！", tag: "问候" },
    { id: "a1-04", de: "Entschuldigung", art: "die", zh: "对不起 / 打扰一下", ipa: "ɛntˈʃʊldɪɡʊŋ", ex: "Entschuldigung, wo ist der Bahnhof?", exZh: "打扰一下，火车站在哪？", tag: "问候" },
    { id: "a1-05", de: "Guten Morgen", art: "", zh: "早上好", ipa: "ˈɡuːtn̩ ˈmɔʁɡn̩", ex: "Guten Morgen, wie geht's?", exZh: "早上好，你好吗？", tag: "问候" },
    { id: "a1-06", de: "Tschüss", art: "", zh: "再见（随意）", ipa: "tʃʏs", ex: "Tschüss, bis morgen!", exZh: "再见，明天见！", tag: "问候" },
    { id: "a1-07", de: "Apfel", art: "der", zh: "苹果", ipa: "ˈapfl̩", ex: "Ich esse einen Apfel.", exZh: "我吃一个苹果。", tag: "食物" },
    { id: "a1-08", de: "Brot", art: "das", zh: "面包", ipa: "bʁoːt", ex: "Das Brot ist frisch.", exZh: "面包很新鲜。", tag: "食物" },
    { id: "a1-09", de: "Kaffee", art: "der", zh: "咖啡", ipa: "ˈkafe", ex: "Einen Kaffee, bitte.", exZh: "请来一杯咖啡。", tag: "食物" },
    { id: "a1-10", de: "Wasser", art: "das", zh: "水", ipa: "ˈvasɐ", ex: "Ich trinke Wasser.", exZh: "我喝水。", tag: "食物" },
    { id: "a1-11", de: "Milch", art: "die", zh: "牛奶", ipa: "mɪlç", ex: "Die Milch ist kalt.", exZh: "牛奶是凉的。", tag: "食物" },
    { id: "a1-12", de: "Haus", art: "das", zh: "房子", ipa: "haʊs", ex: "Das Haus ist klein.", exZh: "这房子很小。", tag: "生活" },
    { id: "a1-13", de: "Stadt", art: "die", zh: "城市", ipa: "ʃtat", ex: "Ich wohne in der Stadt.", exZh: "我住在城里。", tag: "生活" },
    { id: "a1-14", de: "Schule", art: "die", zh: "学校", ipa: "ˈʃuːlə", ex: "Die Schule beginnt um acht.", exZh: "学校八点开始。", tag: "生活" },
    { id: "a1-15", de: "Bahnhof", art: "der", zh: "火车站", ipa: "ˈbaːnhoːf", ex: "Der Bahnhof ist weit.", exZh: "火车站很远。", tag: "出行" },
    { id: "a1-16", de: "Familie", art: "die", zh: "家庭", ipa: "faˈmiːliə", ex: "Meine Familie ist groß.", exZh: "我的家庭很大。", tag: "人物" },
    { id: "a1-17", de: "Freund", art: "der", zh: "朋友（男）", ipa: "fʁɔʏnt", ex: "Das ist mein Freund.", exZh: "这是我的朋友。", tag: "人物" },
    { id: "a1-18", de: "Freundin", art: "die", zh: "朋友（女）", ipa: "ˈfʁɔʏndɪn", ex: "Sie ist meine Freundin.", exZh: "她是我的朋友。", tag: "人物" },
    { id: "a1-19", de: "Kind", art: "das", zh: "孩子", ipa: "kɪnt", ex: "Das Kind spielt.", exZh: "孩子在玩。", tag: "人物" },
    { id: "a1-20", de: "heute", art: "", zh: "今天", ipa: "ˈhɔʏtə", ex: "Heute lerne ich Deutsch.", exZh: "今天我学德语。", tag: "时间" },
    { id: "a1-21", de: "morgen", art: "", zh: "明天", ipa: "ˈmɔʁɡn̩", ex: "Morgen gehe ich ins Kino.", exZh: "明天我去看电影。", tag: "时间" },
    { id: "a1-22", de: "Woche", art: "die", zh: "星期 / 周", ipa: "ˈvɔxə", ex: "Nächste Woche habe ich Zeit.", exZh: "下周我有空。", tag: "时间" },
    { id: "a1-23", de: "wohnen", art: "", zh: "居住", ipa: "ˈvoːnən", ex: "Ich wohne in Berlin.", exZh: "我住在柏林。", tag: "动词" },
    { id: "a1-24", de: "heißen", art: "", zh: "名叫", ipa: "ˈhaɪsn̩", ex: "Ich heiße Lin.", exZh: "我叫林。", tag: "动词" },
    { id: "a1-25", de: "gehen", art: "", zh: "走 / 去", ipa: "ˈɡeːən", ex: "Wir gehen nach Hause.", exZh: "我们回家。", tag: "动词" },
    { id: "a1-26", de: "kommen", art: "", zh: "来", ipa: "ˈkɔmən", ex: "Kommst du aus China?", exZh: "你来自中国吗？", tag: "动词" },
    { id: "a1-27", de: "essen", art: "", zh: "吃", ipa: "ˈɛsn̩", ex: "Was essen wir?", exZh: "我们吃什么？", tag: "动词" },
    { id: "a1-28", de: "trinken", art: "", zh: "喝", ipa: "ˈtʁɪŋkn̩", ex: "Trinkst du Tee?", exZh: "你喝茶吗？", tag: "动词" },
    { id: "a1-29", de: "haben", art: "", zh: "有", ipa: "ˈhaːbn̩", ex: "Ich habe Zeit.", exZh: "我有时间。", tag: "动词" },
    { id: "a1-30", de: "sein", art: "", zh: "是", ipa: "zaɪn", ex: "Ich bin müde.", exZh: "我累了。", tag: "动词" },
    { id: "a1-31", de: "gut", art: "", zh: "好的", ipa: "ɡuːt", ex: "Das ist gut.", exZh: "这很好。", tag: "形容" },
    { id: "a1-32", de: "schön", art: "", zh: "美丽的", ipa: "ʃøːn", ex: "Der Park ist schön.", exZh: "公园很美。", tag: "形容" },
    { id: "a1-33", de: "groß", art: "", zh: "大的", ipa: "ɡʁoːs", ex: "Die Stadt ist groß.", exZh: "这座城市很大。", tag: "形容" },
    { id: "a1-34", de: "klein", art: "", zh: "小的", ipa: "klaɪn", ex: "Ein kleines Café.", exZh: "一家小咖啡馆。", tag: "形容" },
    { id: "a1-35", de: "Zeit", art: "die", zh: "时间", ipa: "tsaɪt", ex: "Hast du Zeit?", exZh: "你有时间吗？", tag: "生活" },
    { id: "a1-36", de: "Name", art: "der", zh: "名字", ipa: "ˈnaːmə", ex: "Wie ist dein Name?", exZh: "你叫什么名字？", tag: "人物" },
  ],
  A2: [
    { id: "a2-01", de: "Reise", art: "die", zh: "旅行", ipa: "ˈʁaɪzə", ex: "Die Reise war schön.", exZh: "这次旅行很美。", tag: "出行" },
    { id: "a2-02", de: "Urlaub", art: "der", zh: "假期", ipa: "ˈuːɐ̯laʊp", ex: "Ich mache Urlaub am Meer.", exZh: "我在海边度假。", tag: "出行" },
    { id: "a2-03", de: "Termin", art: "der", zh: "预约 / 约会", ipa: "tɛʁˈmiːn", ex: "Ich habe um drei einen Termin.", exZh: "我三点有个预约。", tag: "生活" },
    { id: "a2-04", de: "Arzt", art: "der", zh: "医生（男）", ipa: "aːɐ̯tst", ex: "Ich gehe zum Arzt.", exZh: "我去看医生。", tag: "健康" },
    { id: "a2-05", de: "Apotheke", art: "die", zh: "药店", ipa: "apoˈteːkə", ex: "Wo ist die nächste Apotheke?", exZh: "最近的药店在哪？", tag: "健康" },
    { id: "a2-06", de: "Schmerz", art: "der", zh: "疼痛", ipa: "ʃmɛʁts", ex: "Ich habe Kopfschmerzen.", exZh: "我头疼。", tag: "健康" },
    { id: "a2-07", de: "Meinung", art: "die", zh: "意见", ipa: "ˈmaɪnʊŋ", ex: "Was ist deine Meinung?", exZh: "你的意见是什么？", tag: "表达" },
    { id: "a2-08", de: "Idee", art: "die", zh: "主意", ipa: "iˈdeː", ex: "Das ist eine gute Idee.", exZh: "这是个好主意。", tag: "表达" },
    { id: "a2-09", de: "Problem", art: "das", zh: "问题", ipa: "pʁoˈbleːm", ex: "Kein Problem!", exZh: "没问题！", tag: "表达" },
    { id: "a2-10", de: "buchen", art: "", zh: "预订", ipa: "ˈbuːxn̩", ex: "Ich buche ein Zimmer.", exZh: "我订一间房。", tag: "动词" },
    { id: "a2-11", de: "empfehlen", art: "", zh: "推荐", ipa: "ɛmpˈfeːlən", ex: "Was empfehlen Sie?", exZh: "您推荐什么？", tag: "动词" },
    { id: "a2-12", de: "erklären", art: "", zh: "解释", ipa: "ɛɐ̯ˈklɛːʁən", ex: "Kannst du das erklären?", exZh: "你能解释一下吗？", tag: "动词" },
    { id: "a2-13", de: "einkaufen", art: "", zh: "购物", ipa: "ˈaɪnkaʊfn̩", ex: "Wir gehen einkaufen.", exZh: "我们去购物。", tag: "动词" },
    { id: "a2-14", de: "bezahlen", art: "", zh: "付款", ipa: "bəˈtsaːlən", ex: "Ich möchte zahlen, bitte.", exZh: "我想结账。", tag: "动词" },
    { id: "a2-15", de: "Rechnung", art: "die", zh: "账单", ipa: "ˈʁɛçnʊŋ", ex: "Die Rechnung, bitte.", exZh: "请结账。", tag: "生活" },
    { id: "a2-16", de: "Preis", art: "der", zh: "价格", ipa: "pʁaɪs", ex: "Was kostet das? / Der Preis ist gut.", exZh: "这个多少钱？价格不错。", tag: "生活" },
    { id: "a2-17", de: "Wetter", art: "das", zh: "天气", ipa: "ˈvɛtɐ", ex: "Das Wetter ist schlecht.", exZh: "天气不好。", tag: "生活" },
    { id: "a2-18", de: "Wochenende", art: "das", zh: "周末", ipa: "ˈvɔxn̩ˌɛndə", ex: "Am Wochenende bleibe ich zu Hause.", exZh: "周末我待在家里。", tag: "时间" },
    { id: "a2-19", de: "gestern", art: "", zh: "昨天", ipa: "ˈɡɛstɐn", ex: "Gestern war ich müde.", exZh: "昨天我很累。", tag: "时间" },
    { id: "a2-20", de: "schon", art: "", zh: "已经", ipa: "ʃoːn", ex: "Ich bin schon da.", exZh: "我已经到了。", tag: "虚词" },
    { id: "a2-21", de: "noch", art: "", zh: "还 / 仍然", ipa: "nɔx", ex: "Hast du noch Zeit?", exZh: "你还有时间吗？", tag: "虚词" },
    { id: "a2-22", de: "deshalb", art: "", zh: "因此", ipa: "ˈdɛshalp", ex: "Es regnet, deshalb bleibe ich.", exZh: "下雨了，所以我留下。", tag: "虚词" },
    { id: "a2-23", de: "weil", art: "", zh: "因为（从句）", ipa: "vaɪl", ex: "Ich bleibe, weil ich müde bin.", exZh: "我留下，因为我累了。", tag: "虚词" },
    { id: "a2-24", de: "besser", art: "", zh: "更好", ipa: "ˈbɛsɐ", ex: "Heute geht es besser.", exZh: "今天好些了。", tag: "形容" },
    { id: "a2-25", de: "wichtig", art: "", zh: "重要的", ipa: "ˈvɪçtɪç", ex: "Das ist wichtig für mich.", exZh: "这对我很重要。", tag: "形容" },
    { id: "a2-26", de: "möglich", art: "", zh: "可能的", ipa: "ˈmøːklɪç", ex: "Ist das möglich?", exZh: "这可能吗？", tag: "形容" },
    { id: "a2-27", de: "Arbeit", art: "die", zh: "工作", ipa: "ˈaʁbaɪt", ex: "Die Arbeit beginnt früh.", exZh: "工作开始得很早。", tag: "工作" },
    { id: "a2-28", de: "Kollege", art: "der", zh: "同事（男）", ipa: "kɔˈleːɡə", ex: "Mein Kollege hilft mir.", exZh: "我的同事帮我。", tag: "工作" },
    { id: "a2-29", de: "Erfahrung", art: "die", zh: "经验", ipa: "ɛɐ̯ˈfaːʁʊŋ", ex: "Ich habe wenig Erfahrung.", exZh: "我经验不多。", tag: "工作" },
    { id: "a2-30", de: "Einladung", art: "die", zh: "邀请", ipa: "ˈaɪnlaːdʊŋ", ex: "Danke für die Einladung.", exZh: "谢谢邀请。", tag: "社交" },
    { id: "a2-31", de: "treffen", art: "", zh: "见面", ipa: "ˈtʁɛfn̩", ex: "Wir treffen uns um sechs.", exZh: "我们六点见面。", tag: "动词" },
    { id: "a2-32", de: "verstehen", art: "", zh: "理解", ipa: "fɛɐ̯ˈʃteːən", ex: "Ich verstehe nicht.", exZh: "我不明白。", tag: "动词" },
    { id: "a2-33", de: "Wiederholung", art: "die", zh: "重复", ipa: "ˈviːdɐhoːlʊŋ", ex: "Eine Wiederholung, bitte.", exZh: "请再说一遍。", tag: "学习" },
    { id: "a2-34", de: "Fahrkarte", art: "die", zh: "车票", ipa: "ˈfaːɐ̯kartə", ex: "Eine Fahrkarte nach Köln.", exZh: "一张去科隆的票。", tag: "出行" },
    { id: "a2-35", de: "Richtung", art: "die", zh: "方向", ipa: "ˈʁɪçtʊŋ", ex: "In welche Richtung?", exZh: "往哪个方向？", tag: "出行" },
    { id: "a2-36", de: "Glück", art: "das", zh: "幸运 / 幸福", ipa: "ɡlʏk", ex: "Viel Glück!", exZh: "祝你好运！", tag: "表达" },
  ],
  B1: [
    { id: "b1-01", de: "Entscheidung", art: "die", zh: "决定", ipa: "ɛntˈʃaɪdʊŋ", ex: "Das war eine schwere Entscheidung.", exZh: "那是个艰难的决定。", tag: "抽象" },
    { id: "b1-02", de: "Erfahrung", art: "die", zh: "经历 / 经验", ipa: "ɛɐ̯ˈfaːʁʊŋ", ex: "Erzähl von deiner Erfahrung.", exZh: "讲讲你的经历。", tag: "抽象" },
    { id: "b1-03", de: "Umwelt", art: "die", zh: "环境", ipa: "ˈʊmvɛlt", ex: "Wir müssen die Umwelt schützen.", exZh: "我们必须保护环境。", tag: "社会" },
    { id: "b1-04", de: "Gesellschaft", art: "die", zh: "社会", ipa: "ɡəˈzɛlʃaft", ex: "Die Gesellschaft verändert sich.", exZh: "社会在变化。", tag: "社会" },
    { id: "b1-05", de: "trotzdem", art: "", zh: "尽管如此", ipa: "ˈtʁɔtsdeːm", ex: "Es regnet. Trotzdem gehe ich.", exZh: "下雨了。尽管如此我还是去。", tag: "虚词" },
    { id: "b1-06", de: "obwohl", art: "", zh: "虽然", ipa: "ɔpˈvoːl", ex: "Obwohl ich müde bin, lerne ich.", exZh: "虽然累，我还是学。", tag: "虚词" },
    { id: "b1-07", de: "deswegen", art: "", zh: "因此", ipa: "ˈdeːsveːɡn̩", ex: "Der Zug hat Verspätung, deswegen warte ich.", exZh: "火车晚点，所以我等着。", tag: "虚词" },
    { id: "b1-08", de: "sich bewerben", art: "", zh: "申请（职位）", ipa: "bəˈvɛʁbn̩", ex: "Ich bewerbe mich um die Stelle.", exZh: "我申请这个职位。", tag: "工作" },
    { id: "b1-09", de: "Vorstellungsgespräch", art: "das", zh: "面试", ipa: "foːɐ̯ˈʃtɛlʊŋsɡəˌʃpʁɛːç", ex: "Das Vorstellungsgespräch ist morgen.", exZh: "面试在明天。", tag: "工作" },
    { id: "b1-10", de: "verantwortlich", art: "", zh: "负责的", ipa: "fɛɐ̯ˈantvɔʁtlɪç", ex: "Ich bin dafür verantwortlich.", exZh: "我对此负责。", tag: "工作" },
    { id: "b1-11", de: "überzeugen", art: "", zh: "说服 / 使信服", ipa: "yːbɐˈtsɔʏɡn̩", ex: "Das Argument überzeugt mich.", exZh: "这个论点说服了我。", tag: "动词" },
    { id: "b1-12", de: "vorschlagen", art: "", zh: "建议", ipa: "ˈfoːɐ̯ʃlaːɡn̩", ex: "Ich schlage vor, später zu kommen.", exZh: "我建议晚一点来。", tag: "动词" },
    { id: "b1-13", de: "vermeiden", art: "", zh: "避免", ipa: "fɛɐ̯ˈmaɪdn̩", ex: "Wir sollten das vermeiden.", exZh: "我们应该避免这个。", tag: "动词" },
    { id: "b1-14", de: "Entwicklung", art: "die", zh: "发展", ipa: "ɛntˈvɪklʊŋ", ex: "Die Entwicklung ist schnell.", exZh: "发展很快。", tag: "抽象" },
    { id: "b1-15", de: "Lösung", art: "die", zh: "解决方案", ipa: "ˈløːzʊŋ", ex: "Wir brauchen eine Lösung.", exZh: "我们需要一个方案。", tag: "抽象" },
    { id: "b1-16", de: "Beziehung", art: "die", zh: "关系", ipa: "bəˈtsiːʊŋ", ex: "Wir haben eine gute Beziehung.", exZh: "我们关系很好。", tag: "社交" },
    { id: "b1-17", de: "selbstständig", art: "", zh: "独立的", ipa: "ˈzɛlpstʃtɛndɪç", ex: "Sie arbeitet selbstständig.", exZh: "她独立工作。", tag: "形容" },
    { id: "b1-18", de: "zuverlässig", art: "", zh: "可靠的", ipa: "tsuˈfɛɐ̯lɛsɪç", ex: "Er ist sehr zuverlässig.", exZh: "他非常可靠。", tag: "形容" },
    { id: "b1-19", de: "Herausforderung", art: "die", zh: "挑战", ipa: "ˈhɛʁaʊsˌfɔʁdəʁʊŋ", ex: "Das ist eine echte Herausforderung.", exZh: "这是真正的挑战。", tag: "抽象" },
    { id: "b1-20", de: "Alltag", art: "der", zh: "日常生活", ipa: "ˈaltaːk", ex: "Im Alltag spreche ich wenig Deutsch.", exZh: "日常生活中我很少说德语。", tag: "生活" },
    { id: "b1-21", de: "Gewohnheit", art: "die", zh: "习惯", ipa: "ɡəˈvoːnhaɪt", ex: "Lesen ist eine gute Gewohnheit.", exZh: "阅读是个好习惯。", tag: "生活" },
    { id: "b1-22", de: "würde", art: "", zh: "会（虚拟式，委婉）", ipa: "ˈvʏʁdə", ex: "Ich würde gern mitkommen.", exZh: "我很乐意一起去。", tag: "语法" },
    { id: "b1-23", de: "allerdings", art: "", zh: "不过 / 的确", ipa: "ˈalɐdɪŋs", ex: "Die Idee ist gut, allerdings teuer.", exZh: "主意不错，不过贵。", tag: "虚词" },
    { id: "b1-24", de: "zumindest", art: "", zh: "至少", ipa: "tsuˈmɪndəst", ex: "Zumindest versuche ich es.", exZh: "至少我试一试。", tag: "虚词" },
  ],
};

const PHRASES = {
  A1: [
    { de: "Wie heißt du?", zh: "你叫什么名字？", note: "熟人间用 du。" },
    { de: "Ich heiße …", zh: "我叫……", note: "自我介绍第一句。" },
    { de: "Woher kommst du?", zh: "你从哪里来？", note: "问来源，不是问刚才从哪来。" },
    { de: "Ich komme aus China.", zh: "我来自中国。", note: "aus + 国家。" },
    { de: "Wie geht's?", zh: "你好吗？", note: "口语；完整是 Wie geht es dir?" },
    { de: "Gut, danke. Und dir?", zh: "很好，谢谢。你呢？", note: "最稳妥的回法。" },
    { de: "Sprechen Sie Deutsch?", zh: "您说德语吗？", note: "Sie 是尊称。" },
    { de: "Ich verstehe nicht.", zh: "我不明白。", note: "听不懂就说这句，别装懂。" },
    { de: "Langsamer, bitte.", zh: "请慢一点。", note: "比 Wiederholen 更常救场。" },
    { de: "Was kostet das?", zh: "这个多少钱？", note: "点餐、买东西都能用。" },
    { de: "Einen Kaffee, bitte.", zh: "请来一杯咖啡。", note: "点单公式：东西 + bitte。" },
    { de: "Wo ist die Toilette?", zh: "厕所在哪？", note: "永远有用。" },
  ],
  A2: [
    { de: "Können Sie das wiederholen?", zh: "您能再说一遍吗？", note: "比 A1 的「我不懂」更具体。" },
    { de: "Ich hätte gern …", zh: "我想要……（更礼貌）", note: "虚拟式，咖啡馆里很常见。" },
    { de: "Wie komme ich zum Bahnhof?", zh: "去火车站怎么走？", note: "zum = zu dem。" },
    { de: "Ist dieser Platz frei?", zh: "这个位子有人吗？", note: "火车、食堂都能用。" },
    { de: "Ich habe einen Termin um drei.", zh: "我三点有预约。", note: "um + 整点。" },
    { de: "Mir geht es nicht gut.", zh: "我不太舒服。", note: "生病、情绪都能用。" },
    { de: "Was empfehlen Sie?", zh: "您推荐什么？", note: "点菜、买东西都很体面。" },
    { de: "Das war's. Zusammen, bitte.", zh: "就这些。请一起结账。", note: "餐馆收尾。" },
    { de: "Am Wochenende habe ich Zeit.", zh: "周末我有空。", note: "约人的万能句。" },
    { de: "Das gefällt mir.", zh: "这个我喜欢。", note: "gefallen 用 dative：mir。" },
    { de: "Leider kann ich nicht.", zh: "可惜我去不了。", note: "拒绝时先说 leider。" },
    { de: "Bis später!", zh: "回头见！", note: "比 Tschüss 多一点温度。" },
  ],
  B1: [
    { de: "Meiner Meinung nach …", zh: "依我看……", note: "发表观点的开门句。" },
    { de: "Ich bin der Meinung, dass …", zh: "我认为……", note: "dass 从句，动词甩到最后。" },
    { de: "Es kommt darauf an.", zh: "这要看情况。", note: "不想一刀切时很好用。" },
    { de: "Das leuchtet mir ein.", zh: "这我能理解 / 说得通。", note: "比 ja 更有分量。" },
    { de: "Ich würde vorschlagen, dass wir …", zh: "我建议我们……", note: "会议、约事都礼貌。" },
    { de: "Obwohl es schwierig ist, versuche ich es.", zh: "虽然难，我还是试试。", note: "obwohl 从句。" },
    { de: "Trotzdem gebe ich nicht auf.", zh: "尽管如此我也不放弃。", note: "trotzdem 后面是正语序。" },
    { de: "Könnten Sie mir dabei helfen?", zh: "您能在这件事上帮我吗？", note: "können 的虚拟式，更软。" },
    { de: "Im Alltag fällt es mir noch schwer.", zh: "日常生活里我还是觉得难。", note: "诚实又具体。" },
    { de: "Lass uns das anders machen.", zh: "我们换个做法吧。", note: "du 的祈使：lass。" },
    { de: "Das ist eine Herausforderung, aber machbar.", zh: "这是挑战，但做得到。", note: "面试里也好用。" },
    { de: "Ich kümmere mich darum.", zh: "这事我来处理。", note: "sich kümmern um。" },
  ],
};

const DIALOGUES = {
  A1: {
    title: "在咖啡馆",
    lines: [
      { who: "你", de: "Guten Tag! Einen Kaffee, bitte.", zh: "您好！请来一杯咖啡。" },
      { who: "店员", de: "Mit Milch?", zh: "加奶吗？" },
      { who: "你", de: "Ja, ein bisschen. Danke.", zh: "好，一点点。谢谢。" },
      { who: "店员", de: "Das macht 3,20 Euro.", zh: "一共 3.20 欧。" },
    ],
  },
  A2: {
    title: "问路",
    lines: [
      { who: "你", de: "Entschuldigung, wie komme ich zum Museum?", zh: "打扰一下，去博物馆怎么走？" },
      { who: "路人", de: "Gehen Sie geradeaus, dann links.", zh: "一直走，然后左转。" },
      { who: "你", de: "Ist es weit?", zh: "远吗？" },
      { who: "路人", de: "Nein, nur fünf Minuten.", zh: "不远，只要五分钟。" },
    ],
  },
  B1: {
    title: "约改期",
    lines: [
      { who: "你", de: "Leider kann ich morgen nicht. Geht Donnerstag?", zh: "可惜我明天不行。周四可以吗？" },
      { who: "对方", de: "Donnerstag ist schwierig. Freitag Nachmittag?", zh: "周四有点难。周五下午？" },
      { who: "你", de: "Ja, das passt. Um drei?", zh: "可以。三点？" },
      { who: "对方", de: "Einverstanden. Bis Freitag!", zh: "没问题。周五见！" },
    ],
  },
};

const QUIZ = {
  A1: [
    { q: "「谢谢」怎么说？", options: ["Bitte", "Danke", "Hallo", "Tschüss"], a: 1, why: "Danke = 谢谢。Bitte 是「请 / 不客气」。" },
    { q: "Apfel 的冠词是？", options: ["der", "die", "das", "den"], a: 0, why: "der Apfel，阳性。" },
    { q: "「我叫林」", options: ["Ich wohne Lin.", "Ich heiße Lin.", "Ich bin Lin heiße.", "Ich komme Lin."], a: 1, why: "heißen = 名叫。" },
    { q: "Wasser 的冠词是？", options: ["der", "die", "das", "dem"], a: 2, why: "das Wasser，中性。" },
    { q: "点咖啡最自然的说法？", options: ["Ich will Kaffee jetzt.", "Kaffee ich bitte.", "Einen Kaffee, bitte.", "Der Kaffee, danke."], a: 2, why: "点单：Akkusativ + bitte。" },
    { q: "Milch 的冠词是？", options: ["der", "die", "das", "den"], a: 1, why: "die Milch，阴性。" },
    { q: "「你从哪里来？」", options: ["Wo wohnst du?", "Woher kommst du?", "Wie kommst du?", "Was kommst du?"], a: 1, why: "woher = 从何处来。" },
    { q: "Tschüss 的语气是？", options: ["非常正式", "随意告别", "只用于早晨", "表示抱歉"], a: 1, why: "熟人间的再见。正式场合用 Auf Wiedersehen。" },
    { q: "「我住在柏林」", options: ["Ich heiße in Berlin.", "Ich gehe Berlin.", "Ich wohne in Berlin.", "Ich komme in Berlin."], a: 2, why: "wohnen in + 城市。" },
    { q: "Haus 的冠词是？", options: ["der", "die", "das", "den"], a: 2, why: "das Haus，中性。" },
    { q: "Guten Morgen 用于？", options: ["晚上", "上午", "分别时", "点餐"], a: 1, why: "早上好 / 上午好。" },
    { q: "「我不明白」", options: ["Ich bin nicht.", "Ich habe nicht.", "Ich verstehe nicht.", "Ich gehe nicht."], a: 2, why: "verstehen = 理解。" },
  ],
  A2: [
    { q: "「因此」最贴近的词？", options: ["weil", "deshalb", "schon", "noch"], a: 1, why: "deshalb 连接两个主句。weil 引导从句。" },
    { q: "Ich bleibe, ___ ich müde bin.", options: ["deshalb", "und", "weil", "aber"], a: 2, why: "weil 从句：动词 bin 在句末。" },
    { q: "礼貌点单常用？", options: ["Ich will …", "Gib mir …", "Ich hätte gern …", "Mach …"], a: 2, why: "hätte gern 是客气的虚拟式。" },
    { q: "「结账」怎么说？", options: ["Die Reise, bitte.", "Die Rechnung, bitte.", "Der Termin, bitte.", "Die Meinung, bitte."], a: 1, why: "Rechnung = 账单。" },
    { q: "gefallen 搭配谁？", options: ["Das gefällt ich.", "Das gefällt mir.", "Das gefällt mich.", "Das gefällt mein."], a: 1, why: "gefallen + 第三格：mir。" },
    { q: "Arzt 是？", options: ["药店", "预约", "医生", "疼痛"], a: 2, why: "der Arzt。药店是 die Apotheke。" },
    { q: "「昨天」", options: ["heute", "morgen", "gestern", "schon"], a: 2, why: "gestern / heute / morgen。" },
    { q: "Fahrkarte 是？", options: ["方向", "车票", "假期", "同事"], a: 1, why: "die Fahrkarte = 车票。" },
    { q: "约见面：我们六点见面。", options: ["Wir gehen uns um sechs.", "Wir treffen uns um sechs.", "Wir wohnen uns um sechs.", "Wir zahlen uns um sechs."], a: 1, why: "sich treffen。" },
    { q: "Wochenende 的冠词？", options: ["der", "die", "das", "den"], a: 2, why: "das Wochenende。" },
    { q: "「没问题」", options: ["Kein Problem!", "Kein Preis!", "Kein Wetter!", "Kein Termin!"], a: 0, why: "口语里极常用。" },
    { q: "empfehlen 意思是？", options: ["付款", "预订", "推荐", "解释"], a: 2, why: "Was empfehlen Sie?" },
  ],
  B1: [
    { q: "obwohl 后面的语序？", options: ["正语序，动词第二位", "从句，动词在末尾", "永远倒装", "可以省略动词"], a: 1, why: "Obwohl ich müde bin, …" },
    { q: "trotzdem 后面通常是？", options: ["从句语序", "正语序主句", "必须用 weil", "只能用过去时"], a: 1, why: "Trotzdem gehe ich. 动词仍在第二位。" },
    { q: "「依我看」", options: ["Meiner Meinung nach …", "Meine Meinung nach …", "Nach ich Meinung …", "Mein Meinung ist nach …"], a: 0, why: "meiner 是阴性和单数第三格。" },
    { q: "Ich würde gern mitkommen. 语气是？", options: ["命令", "过去完成", "委婉愿望", "正在进行"], a: 2, why: "würde + 不定式，虚拟式礼貌说法。" },
    { q: "sich bewerben um 是？", options: ["负责某事", "申请某职位", "避免某事", "说服某人"], a: 1, why: "Ich bewerbe mich um die Stelle." },
    { q: "「这要看情况」", options: ["Das leuchtet mir ein.", "Es kommt darauf an.", "Ich kümmere mich darum.", "Das war's."], a: 1, why: "es kommt darauf an。" },
    { q: "Herausforderung 是？", options: ["习惯", "挑战", "环境", "关系"], a: 1, why: "die Herausforderung。" },
    { q: "Umwelt 的冠词？", options: ["der", "die", "das", "den"], a: 1, why: "die Umwelt。" },
    { q: "「这事我来处理」", options: ["Ich vermeide das.", "Ich überzeuge das.", "Ich kümmere mich darum.", "Ich bewerbe das."], a: 2, why: "sich kümmern um。" },
    { q: "allerdings 最接近？", options: ["因为", "不过 / 的确", "已经", "至少"], a: 1, why: "让步或加强：主意好，不过贵。" },
    { q: "dass 从句里动词在？", options: ["最前面", "第二位", "句末", "可以丢掉"], a: 2, why: "Ich bin der Meinung, dass das stimmt." },
    { q: "zumindest 意思是？", options: ["尽管如此", "因此", "至少", "虽然"], a: 2, why: "Zumindest versuche ich es." },
  ],
};

const GRAMMAR = {
  A1: [
    { t: "三个冠词", d: "der 阳、die 阴、das 中。记单词请连冠词一起记，别只记 Apfel。" },
    { t: "动词第二位", d: "陈述句里变位动词在第二位置：Ich lerne Deutsch. Heute lerne ich Deutsch." },
    { t: "du / Sie", d: "熟人用 du，店员、陌生人和正式场合用 Sie。点餐默认 Sie。" },
    { t: "点单公式", d: "Einen Kaffee, bitte. 点的东西常用第四格，后面加 bitte 就很得体。" },
  ],
  A2: [
    { t: "weil 把动词踢到最后", d: "Ich bleibe, weil ich müde bin. 逗号后是从句，bin 在末尾。" },
    { t: "deshalb 不踢动词", d: "Ich bin müde, deshalb bleibe ich. deshalb 后仍是正常主句。" },
    { t: "完成时 haben / sein", d: "大多数动词用 haben：Ich habe gegessen. 位移和变化常用 sein：Ich bin gegangen." },
    { t: "第三格的人", d: "gefallen、helfen、danken 后面是人的第三格：Das gefällt mir." },
  ],
  B1: [
    { t: "obwohl vs trotzdem", d: "obwohl = 虽然（从句）；trotzdem = 尽管如此（主句）。一对姐妹，语序不同。" },
    { t: "würde + 不定式", d: "Ich würde gern … 用来提建议、说愿望，比直接说 will 软。" },
    { t: "dass 从句", d: "Ich glaube, dass das geht. 连接词 dass 后，动词去句末。" },
    { t: "反身动词", d: "sich treffen、sich bewerben、sich kümmern。主语做、主语也承受：Wir treffen uns." },
  ],
};

const FOX = [
  "别贪多。今天把一张卡片念出声，就算赢。",
  "冠词要跟单词绑在一起：不是 Apfel，是 der Apfel。",
  "听不懂就说 Langsamer, bitte. 这是勇气，不是丢脸。",
  "德语听起来硬，是因为辅音多。慢一点，它会软下来。",
  "连续几天比一次学两小时更有用。练习本喜欢回头看的人。",
  "句子比单词名单更值钱。把今日单词放进你自己的生活里。",
];
